# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tom/common/tom.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14tom/common/tom.proto\x12\x03tom\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcc\x01\n\x15\x44istanceMatrixRequest\x12\x18\n\x03lat\x18\x01 \x01(\x0b\x32\x0b.tom.Vector\x12\x18\n\x03lon\x18\x02 \x01(\x0b\x32\x0b.tom.Vector\x12\x16\n\x0etransport_mode\x18\x03 \x01(\t\x12\x32\n\x0e\x64\x65parture_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05\x61void\x18\x05 \x03(\t\x12\r\n\x05units\x18\x06 \x01(\t\x12\x15\n\rtraffic_model\x18\x07 \x01(\t\"V\n\x16\x44istanceMatrixResponse\x12\x1d\n\tdurations\x18\x01 \x01(\x0b\x32\n.tom.Array\x12\x1d\n\tdistances\x18\x02 \x01(\x0b\x32\n.tom.Array\"t\n\x0fTimeZoneRequest\x12\x18\n\x03lat\x18\x01 \x01(\x0b\x32\x0b.tom.Vector\x12\x18\n\x03lon\x18\x02 \x01(\x0b\x32\x0b.tom.Vector\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"8\n\x10TimeZoneResponse\x12$\n\x0ftimezone_offset\x18\x01 \x01(\x0b\x32\x0b.tom.Vector\"\x1a\n\x06Vector\x12\x10\n\x08\x65lements\x18\x01 \x03(\x02\"\"\n\x05\x41rray\x12\x19\n\x04rows\x18\x01 \x03(\x0b\x32\x0b.tom.Vector2\x9a\x01\n\nGoogleMaps\x12N\n\x11GetDistanceMatrix\x12\x1a.tom.DistanceMatrixRequest\x1a\x1b.tom.DistanceMatrixResponse\"\x00\x12<\n\x0bGetTimeZone\x12\x14.tom.TimeZoneRequest\x1a\x15.tom.TimeZoneResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tom.common.tom_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DISTANCEMATRIXREQUEST._serialized_start=63
  _DISTANCEMATRIXREQUEST._serialized_end=267
  _DISTANCEMATRIXRESPONSE._serialized_start=269
  _DISTANCEMATRIXRESPONSE._serialized_end=355
  _TIMEZONEREQUEST._serialized_start=357
  _TIMEZONEREQUEST._serialized_end=473
  _TIMEZONERESPONSE._serialized_start=475
  _TIMEZONERESPONSE._serialized_end=531
  _VECTOR._serialized_start=533
  _VECTOR._serialized_end=559
  _ARRAY._serialized_start=561
  _ARRAY._serialized_end=595
  _GOOGLEMAPS._serialized_start=598
  _GOOGLEMAPS._serialized_end=752
# @@protoc_insertion_point(module_scope)
